### PR TITLE
Separate filmSummary and filmRelationship calls

### LINKED ISSUE #28: Crash: film details when not signed in
It's calling the film relationship endpoint - can't do that without token.

### PR DESCRIPTION
**Pull request by ataulm**
- if user isn't signed in, they can't load film relationship
- we hide those sections if film relationship isn't loaded

fixes #28

### CODE REVIEW

File: app/src/main/java/com/ataulm/whatsnext/TokensStore.kt [hunk 1]
```diff
@@ -19,6 +19,8 @@ class TokensStore private constructor(private val preferences: SharedPreferences
                 .apply()
     }
 
+    fun userIsSignedIn() = token != null
```
Comment (ataulm) [inline app/src/main/java/com/ataulm/whatsnext/TokensStore.kt:22]: This is a rudimentary check for whether the user is signed in. There's no way to tell in advance of making an API call and there's no way to guarantee that they will still be signed in after that (e.g. the token could expire immediately after we check).

This lets us head off the case where we _know_ the user isn't signed in. We'll have to deal with errors separately (e.g. network failure, missing refresh token etc)

File: app/src/main/java/com/ataulm/whatsnext/WhatsNextRepository.kt [hunk 2]
```diff
@@ -34,13 +37,14 @@ internal class WhatsNextRepository(
         filmSummaries
     }
 
-    suspend fun film(letterboxdId: String) = withContext(Dispatchers.IO) {
+    suspend fun filmSummary(letterboxdId: String) = withContext(Dispatchers.IO) {
```
Comment (ataulm) [inline app/src/main/java/com/ataulm/whatsnext/WhatsNextRepository.kt:40]: technically, letterboxd has different responses for a film/filmsummary. A `FilmSummary` is usually general info about the film, pretty light, and is returned from other API calls like the one we use for popular films this week.

Even though we're getting a full film back here from the API, we're using the film Summary converter so we're ignoring a bunch of properties, hence the rename for this function.

File: app/src/main/java/com/ataulm/whatsnext/WhatsNextRepository.kt [hunk 3]
```diff
@@ -34,13 +37,14 @@ internal class WhatsNextRepository(
...
         val apiFilm = letterboxdApi.film(letterboxdId)
+        filmSummaryConverter.convert(apiFilm)
+    }
+
+    suspend fun filmRelationship(letterboxdId: String) = withContext(Dispatchers.IO) {
```
Comment (ataulm) [inline app/src/main/java/com/ataulm/whatsnext/WhatsNextRepository.kt:45]: had to extract this because this only works if the user is signed in, and that wasn't necessarily the case where we were calling `film` before.

File: app/src/main/java/com/ataulm/whatsnext/WhatsNextRepository.kt [hunk 4]
```diff
@@ -59,13 +63,8 @@ internal class WhatsNextRepository(
...
                 )
         )
-        // TODO: this is wasteful - the filmSummary won't have changed.
-        val apiFilm = letterboxdApi.film(letterboxdId)
         val apiFilmRelationship = apiFilmRelationshipUpdateResponse.data
-        Film(
-                filmSummaryConverter.convert(apiFilm),
-                filmRelationshipConverter.convert(apiFilmRelationship)
-        )
+        filmRelationshipConverter.convert(apiFilmRelationship)
```
Comment (ataulm) [inline app/src/main/java/com/ataulm/whatsnext/WhatsNextRepository.kt:67]: when we're updating a film relationship (whether user likes it/watched it etc), the summary of the film doesn't change - there's no need to load it again.
